Java06. ДЗ 03, Kurbanov Rauf
Rauf-Kurbanov/AU-java-course pull request #12
Opened 2016-10-18 19:23 UTC by Rauf-Kurbanov

@sproshev

2016-10-26 19:54 UTC, sproshev requested changes
надо исправлять

2016-10-26 19:54 UTC, sproshev commented on ftp/src/main/java/client/FtpClient.java
> +    final Protocol protocol = new FtpProtocol();
протоколу почему-то не досталось модификатора доступа ((((

2016-10-26 19:54 UTC, sproshev commented on ftp/src/main/java/client/FtpClient.java
> +        clientSocket.close();
достаточно только сокет закрыть

2016-10-26 19:54 UTC, sproshev commented on ftp/src/main/java/protocol/Protocol.java
> +    void answerGet(String path, DataOutputStream output) throws IOException;
почему последние два метода так названы, если они ни на что не "отвечают"?

2016-10-26 19:54 UTC, sproshev commented on ftp/src/main/java/server/FtpServer.java
> +                Socket clientSocket = serverSocket.accept();
сервер принимает только 1 подключение и перестает работать? -1

2016-10-26 19:54 UTC, sproshev commented on ftp/src/main/java/server/FtpServer.java
> +            System.out.println(e.getMessage());
сообщение не всегда соответствует действительности

2016-10-26 19:54 UTC, sproshev commented on ftp/src/test/java/protocol/FtpProtocolTest.java
> +}
тест захламлен, много Unused, надо приводить в порядок

2016-10-26 19:54 UTC, sproshev commented on ftp/src/test/java/server/FtpServerTest.java
> +}
здесь то же самое

2016-10-26 19:54 UTC, sproshev commented on ftp/src/test/java/server/FtpServerTest.java
> +}
не провереные крайние случаи -- несуществующая директория, напр.

2016-10-28 14:18 UTC, Rauf-Kurbanov commented on ftp/src/main/java/protocol/Protocol.java
> +    void answerGet(String path, DataOutputStream output) throws IOException;
+

2016-10-28 14:22 UTC, Rauf-Kurbanov commented on ftp/src/test/java/protocol/FtpProtocolTest.java
> +}
+

2016-10-28 14:25 UTC, Rauf-Kurbanov commented on ftp/src/test/java/server/FtpServerTest.java
> +}
+

2016-10-28 14:33 UTC, Rauf-Kurbanov commented on ftp/src/main/java/server/FtpServer.java
> +            System.out.println(e.getMessage());
+

2016-10-28 14:33 UTC, Rauf-Kurbanov commented on ftp/src/main/java/client/FtpClient.java
> +        clientSocket.close();
+

2016-10-28 14:34 UTC, Rauf-Kurbanov commented on ftp/src/main/java/client/FtpClient.java
> +    final Protocol protocol = new FtpProtocol();
+

2016-10-29 15:34 UTC, Rauf-Kurbanov commented on ftp/src/test/java/server/FtpServerTest.java
> +}
+

2016-11-01 22:57 UTC, Rauf-Kurbanov commented on ftp/src/main/java/server/FtpServer.java
> +                Socket clientSocket = serverSocket.accept();
+

2016-12-13 16:51 UTC, merged